- title: "Жилищно строителство"
  icon: "/assets/images/services/residential.svg"
  description: "Изграждане на жилищни сгради, еднофамилни къщи, изкопи, събаряне на стари сгради, извозване на земни маси, доставка на скални фракции и др."
  gallery_id: "home"
  gallery_images:
   - "/assets/images/home/IMG_7984.JPG"
   - "/assets/images/home/IMG_7985.JPG"
   - "/assets/images/home/IMG_7987.JPG"
   - "/assets/images/home/IMG_7988.JPG"
   - "/assets/images/home/IMG_7989.JPG"
   - "/assets/images/home/IMG_8173.JPG"
   - "/assets/images/home/IMG_8174.JPG"
   - "/assets/images/home/IMG_8177.JPG"
   - "/assets/images/home/IMG_8179.JPG"
   - "/assets/images/home/IMG_8180.JPG"
   - "/assets/images/home/IMG_8182.JPG"
   - "/assets/images/home/IMG_8183.JPG"
   - "/assets/images/home/IMG_8357.JPG"
   - "/assets/images/home/IMG_8358.JPG"
   - "/assets/images/home/IMG_8359.JPG"
   - "/assets/images/home/IMG_8360.JPG"
   - "/assets/images/home/IMG_8361.JPG"
   - "/assets/images/home/IMG_8362.JPG"
   - "/assets/images/home/IMG_8394.JPG"
   - "/assets/images/home/IMG_8389.JPG"
   - "/assets/images/home/IMG_8387.JPG"
   - "/assets/images/home/IMG_8067.JPG"
   - "/assets/images/home/IMG_8066.JPG"
   - "/assets/images/home/IMG_8024.JPG"
   - "/assets/images/home/IMG_8399.JPG"
   - "/assets/images/home/IMG_8389.JPG"
   - "/assets/images/home/IMG_8442.JPG"
   - "/assets/images/home/IMG_8441.JPG"
   - "/assets/images/home/IMG_8440.JPG"
   - "/assets/images/home/IMG_8439.JPG"
   - "/assets/images/home/IMG_8438.JPG"
   - "/assets/images/home/IMG_8437.JPG"
   - "/assets/images/home/IMG_8436.JPG"
   - "/assets/images/home/IMG_8435.JPG"
   - "/assets/images/home/IMG_8434.JPG"
   - "/assets/images/home/IMG_8433.JPG"
   - "/assets/images/home/IMG_8430.JPG"
   - "/assets/images/home/IMG_8429.JPG"
   - "/assets/images/home/IMG_8428.JPG"
   - "/assets/images/home/IMG_8427.JPG"
   - "/assets/images/home/IMG_8655.JPG"
   - "/assets/images/home/IMG_8656.JPG"
   - "/assets/images/home/IMG_8657.JPG"
   - "/assets/images/home/IMG_8673.JPG"
   - "/assets/images/home/IMG_8674.JPG"
   - "/assets/images/home/IMG_8699.JPG"
   - "/assets/images/home/IMG_8697.JPG"
   - "/assets/images/home/IMG_8696.JPG"
   - "/assets/images/home/IMG_8695.JPG"
   - "/assets/images/home/IMG_8689.JPG"
   - "/assets/images/home/IMG_8688.JPG"
   - "/assets/images/home/IMG_8694.JPG"
   - "/assets/images/home/IMG_8692.JPG"
   - "/assets/images/home/IMG_8691.JPG"
   - "/assets/images/home/IMG_8690.JPG"
   - "/assets/images/home/IMG_8700.JPG"
   - "/assets/images/home/IMG_8701.JPG"
   - "/assets/images/home/IMG_8702.JPG"
   - "/assets/images/home/IMG_8703.JPG"
   - "/assets/images/home/IMG_8704.JPG"
   - "/assets/images/home/IMG_8705.JPG"
   - "/assets/images/home/IMG_8707.JPG"
   - "/assets/images/home/IMG_8708.JPG"
   - "/assets/images/home/IMG_8721.JPG"
   - "/assets/images/home/IMG_8722.JPG"
   - "/assets/images/home/IMG_8723.JPG"
   - "/assets/images/home/IMG_8724.JPG"
   - "/assets/images/home/IMG_8725.JPG"
   - "/assets/images/home/IMG_8742.JPG"
   - "/assets/images/home/IMG_8743.JPG"
   - "/assets/images/home/IMG_8744.JPG"
   - "/assets/images/home/IMG_8745.JPG"
   - "/assets/images/home/IMG_8746.JPG"
   
- title: "Ремонтни дейности"
  icon: "/assets/images/services/renovation.svg"
  description: "Вътрешни и външни цялостни и частични ремонти, покривни и дървени конструкции, фасади, хидро и топлоизолации."
  gallery_id: "ремонтни-дейности"
  gallery_images:
    - "/assets/images/ime na papka/nomer na snimka.JPG"
    
- title: "Басейни и Spa комплекси"
  icon: "/assets/images/services/commercial.svg"
  description: "Изграждане на басейни и цялостни Spa комплекси с високо качество на изпълнение."
  gallery_id: "басейни-и-spa-комплекси"
  gallery_images:
    - "/assets/images/ime na papka/nomer na snimka.JPG"
  
      
- title: "Довършителни дейности"
  icon: "/assets/images/services/industrial.svg"
  description: "Финна шпакловка, машинно боядисване, декоративни мазилки, гранитогрес, каменни облицовки, вътрешни и външни мазилки."
  gallery_id: "довършителни-дейности"
  gallery_images:
    - "/assets/images/ime na papka/nomer na snimka.JPG"
    
- title: "ОВК, ВиК и ел. инсталации"
  icon: "/assets/images/services/infrastructure.svg"
  description: "Изграждане на ОВК, ВиК и електро инсталации, подово отопление и други специализирани инсталации."
  gallery_id: "овк-вик-и-ел-инсталации"
  gallery_images:
    - "/assets/images/ime na papka/nomer na snimka.JPG"

- title: "Архитектурно проектиране и Геодезия"
  icon: "/assets/images/services/architecture.svg"
  description: "Изготвяне на архитектурни проекти, технически чертежи и 3D визуализации."
  gallery_id: "архитектурно-проектиране"
  gallery_images:
    - "/assets/images/ime na papka/nomer na snimka.JPG"
    
    
