- title: "Жилищно строителство"
  icon: "/assets/images/services/residential.svg"
  description: "Изграждане на жилищни сгради, еднофамилни къщи, изкопи, събаряне на стари сгради, извозване на земни маси, доставка на скални фракции и др."
  gallery_id: "home"
  gallery_images:
    - "/assets/images/home/IMG_7983.JPG"
    - "/assets/images/home/IMG_7984.JPG"
    - "/assets/images/home/IMG_7985.JPG"
    - "/assets/images/home/IMG_7986.JPG"
    - "/assets/images/home/IMG_7987.JPG"
    - "/assets/images/home/IMG_7988.JPG"
    - "/assets/images/home/IMG_7989.JPG"

- title: "Ремонтни дейности"
  icon: "/assets/images/services/renovation.svg"
  description: "Вътрешни и външни цялостни и частични ремонти, покривни и дървени конструкции, фасади, хидро и топлоизолации."
  gallery_id: "ремонтни-дейности"
  gallery_images:
    - "/assets/images/reconstruction/1.JPG"
    - "/assets/images/reconstruction/2.JPG"
    - "/assets/images/reconstruction/3.JPG"
    - "/assets/images/reconstruction/4.JPG"
    - "/assets/images/reconstruction/5.JPG"
    - "/assets/images/reconstruction/6.JPG"
    - "/assets/images/reconstruction/7.JPG"
    - "/assets/images/reconstruction/8.JPG"
    - "/assets/images/reconstruction/9.JPG"
    - "/assets/images/reconstruction/10.JPG"
    - "/assets/images/reconstruction/11.JPG"
    - "/assets/images/reconstruction/12.JPG"
    - "/assets/images/reconstruction/13.JPG"
    - "/assets/images/reconstruction/14.JPG"
    - "/assets/images/reconstruction/29.1.2.JPG"
    - "/assets/images/reconstruction/29.1.3.JPG"
    - "/assets/images/reconstruction/29.1.4.JPG"
    - "/assets/images/reconstruction/29.3.JPG"
    - "/assets/images/reconstruction/29.4.JPG"
    - "/assets/images/reconstruction/29.5.JPG"
    - "/assets/images/reconstruction/29.6.JPG"
    - "/assets/images/reconstruction/29.7.JPG"
    - "/assets/images/reconstruction/29.8.JPG"
    - "/assets/images/reconstruction/IMG_8036.JPG"
    - "/assets/images/reconstruction/IMG_8037.JPG"
    - "/assets/images/reconstruction/IMG_8038.JPG"
    - "/assets/images/reconstruction/IMG_8039.JPG"
    - "/assets/images/reconstruction/IMG_8040.JPG"
    - "/assets/images/reconstruction/IMG_8041.JPG"
    - "/assets/images/reconstruction/IMG_8045.JPG"
    - "/assets/images/reconstruction/IMG_8046.JPG"
    - "/assets/images/reconstruction/IMG_8047.JPG"
    - "/assets/images/reconstruction/IMG_8048.JPG"
    - "/assets/images/reconstruction/IMG_8049.JPG"
    - "/assets/images/reconstruction/IMG_8050.JPG"
    - "/assets/images/reconstruction/IMG_8051.JPG"
    - "/assets/images/reconstruction/IMG_8052.JPG"
    - "/assets/images/reconstruction/IMG_8055.JPG"
    - "/assets/images/reconstruction/IMG_8073.JPG"
    - "/assets/images/reconstruction/IMG_8072.JPG"
    - "/assets/images/reconstruction/IMG_8071.JPG"
    - "/assets/images/reconstruction/IMG_8082.JPG"
    - "/assets/images/reconstruction/IMG_8083.JPG"
    - "/assets/images/reconstruction/IMG_8084.JPG"
    - "/assets/images/reconstruction/IMG_8085.JPG"
    - "/assets/images/reconstruction/IMG_8086.JPG"
    - "/assets/images/reconstruction/IMG_8087.JPG"
    - "/assets/images/reconstruction/IMG_8088.JPG"
    - "/assets/images/reconstruction/IMG_8089.JPG"
    - "/assets/images/reconstruction/IMG_8090.JPG"
    - "/assets/images/reconstruction/IMG_8091.JPG"
    - "/assets/images/reconstruction/IMG_8092.JPG"
    - "/assets/images/reconstruction/IMG_8093.JPG"
    - "/assets/images/reconstruction/IMG_8094.JPG"
    - "/assets/images/reconstruction/IMG_8095.JPG"
    - "/assets/images/reconstruction/IMG_8102.JPG"
    - "/assets/images/reconstruction/IMG_8103.JPG"
    - "/assets/images/reconstruction/IMG_8104.JPG"
    - "/assets/images/reconstruction/IMG_8105.JPG"
    - "/assets/images/reconstruction/IMG_8106.JPG"
    - "/assets/images/reconstruction/IMG_8168.JPG"
    - "/assets/images/reconstruction/IMG_8169.JPG"
    - "/assets/images/reconstruction/IMG_8170.JPG"
    - "/assets/images/reconstruction/IMG_8209.JPG"
    - "/assets/images/reconstruction/IMG_8210.JPG"
    - "/assets/images/reconstruction/IMG_8212.JPG"
    - "/assets/images/reconstruction/IMG_8213.JPG"
    - "/assets/images/reconstruction/IMG_8214.JPG"
    - "/assets/images/reconstruction/IMG_8215.JPG"
    - "/assets/images/reconstruction/IMG_8216.JPG"
    - "/assets/images/reconstruction/IMG_8217.JPG"
    - "/assets/images/reconstruction/IMG_8379.JPG"
    - "/assets/images/reconstruction/IMG_8380.JPG"
    - "/assets/images/reconstruction/IMG_8381.JPG"
    - "/assets/images/reconstruction/IMG_8407.JPG"
    - "/assets/images/reconstruction/IMG_8406.JPG"
    - "/assets/images/reconstruction/IMG_8405.JPG"
    - "/assets/images/reconstruction/IMG_8404.JPG"
    - "/assets/images/reconstruction/IMG_8403.JPG"
    - "/assets/images/reconstruction/IMG_8401.JPG"
    - "/assets/images/reconstruction/IMG_8530.JPG"
    - "/assets/images/reconstruction/IMG_8529.JPG"
    - "/assets/images/reconstruction/IMG_8528.JPG"
    - "/assets/images/reconstruction/IMG_8527.JPG"
    - "/assets/images/reconstruction/IMG_8526.JPG"
    - "/assets/images/reconstruction/IMG_8525.JPG"
    - "/assets/images/reconstruction/IMG_8524.JPG"
    - "/assets/images/reconstruction/IMG_8523.JPG"
    - "/assets/images/reconstruction/IMG_8522.JPG"
    - "/assets/images/reconstruction/IMG_8521.JPG"
    - "/assets/images/reconstruction/IMG_8520.JPG"
    - "/assets/images/reconstruction/IMG_8519.JPG"
    - "/assets/images/reconstruction/IMG_8518.JPG"
    - "/assets/images/reconstruction/IMG_8517.JPG"
    - "/assets/images/reconstruction/IMG_8516.JPG"
    - "/assets/images/reconstruction/IMG_8515.JPG"
    - "/assets/images/reconstruction/IMG_8514.JPG"
    - "/assets/images/reconstruction/IMG_8513.JPG"
    - "/assets/images/reconstruction/IMG_8547.JPG"
    - "/assets/images/reconstruction/IMG_8574.JPG"
    - "/assets/images/reconstruction/IMG_8575.JPG"
    - "/assets/images/reconstruction/IMG_8576.JPG"
    - "/assets/images/reconstruction/IMG_8586.JPG"
    - "/assets/images/reconstruction/IMG_8614.JPG"
    - "/assets/images/reconstruction/IMG_8615.JPG"
    - "/assets/images/reconstruction/IMG_8616.JPG"
    - "/assets/images/reconstruction/IMG_8617.JPG"
    - "/assets/images/reconstruction/IMG_8618.JPG"
    - "/assets/images/reconstruction/IMG_8620.JPG"
    - "/assets/images/reconstruction/IMG_8621.JPG"
    - "/assets/images/reconstruction/IMG_8622.JPG"
    - "/assets/images/reconstruction/IMG_8709.JPG"
    - "/assets/images/reconstruction/IMG_8710.JPG"
    - "/assets/images/reconstruction/IMG_8711.JPG"
    - "/assets/images/reconstruction/IMG_8712.JPG"
    - "/assets/images/reconstruction/IMG_8713.JPG"
    - "/assets/images/reconstruction/IMG_8714.JPG"
    - "/assets/images/reconstruction/IMG_8715.JPG"
    - "/assets/images/reconstruction/IMG_8716.JPG"
    - "/assets/images/reconstruction/IMG_8717.JPG"
    - "/assets/images/reconstruction/IMG_8718.JPG"
    - "/assets/images/reconstruction/IMG_8719.JPG"
    - "/assets/images/reconstruction/IMG_8720.JPG"
    - "/assets/images/reconstruction/IMG_8726.JPG"
    - "/assets/images/reconstruction/IMG_8727.JPG"
    - "/assets/images/reconstruction/IMG_8728.JPG"
    - "/assets/images/reconstruction/IMG_8729.JPG"
    - "/assets/images/reconstruction/IMG_8730.JPG"
    - "/assets/images/reconstruction/IMG_8731.JPG"
    - "/assets/images/reconstruction/IMG_8732.JPG"
    - "/assets/images/reconstruction/IMG_8733.JPG"
    - "/assets/images/reconstruction/IMG_8734.JPG"
    - "/assets/images/reconstruction/IMG_8735.JPG"
    - "/assets/images/reconstruction/IMG_8736.JPG"
    - "/assets/images/reconstruction/IMG_8737.JPG"
    - "/assets/images/reconstruction/IMG_8738.JPG"
    - "/assets/images/reconstruction/IMG_8739.JPG"
    - "/assets/images/reconstruction/IMG_8740.JPG"
    - "/assets/images/reconstruction/IMG_8741.JPG"
    
- title: "Басейни и Spa комплекси"
  icon: "/assets/images/services/commercial.svg"
  description: "Изграждане на басейни и цялостни Spa комплекси с високо качество на изпълнение."
  gallery_id: "басейни-и-spa-комплекси"
  gallery_images:
    - "/assets/images/spa/1.JPG"
    - "/assets/images/spa/2.JPG"
    - "/assets/images/spa/3.JPG"
    - "/assets/images/spa/4.JPG"
    - "/assets/images/spa/5.JPG"
    - "/assets/images/spa/6.JPG"
    - "/assets/images/spa/7.JPG"
    - "/assets/images/spa/8.JPG"
    - "/assets/images/spa/9.1.JPG"
    - "/assets/images/spa/9.2.JPG"
    - "/assets/images/spa/9.JPG"
    - "/assets/images/spa/10.JPG"
    - "/assets/images/spa/11.JPG"
    - "/assets/images/spa/12.JPG"
    - "/assets/images/spa/13.JPG"
    - "/assets/images/spa/14.JPG"
    - "/assets/images/spa/15.JPG"
    - "/assets/images/spa/16.JPG"
    - "/assets/images/spa/17.JPG"
    - "/assets/images/spa/18.JPG"
    - "/assets/images/spa/19.JPG"
    - "/assets/images/spa/20.JPG"
    - "/assets/images/spa/21.JPG"
    - "/assets/images/spa/22.JPG"
    - "/assets/images/spa/23.JPG"
    - "/assets/images/spa/24.JPG"
    - "/assets/images/spa/25.JPG"
    - "/assets/images/spa/26.JPG"
    - "/assets/images/spa/27.JPG"
    - "/assets/images/spa/28.1.JPG"
    - "/assets/images/spa/28.2.JPG"
    - "/assets/images/spa/28.3.JPG"
    - "/assets/images/spa/28.JPG"
    - "/assets/images/spa/29.JPG"
    - "/assets/images/spa/30.JPG"
    - "/assets/images/spa/31.JPG"
    - "/assets/images/spa/32.JPG"
    - "/assets/images/spa/33.JPG"
    - "/assets/images/spa/34.JPG"
    - "/assets/images/spa/35.JPG"
    - "/assets/images/spa/36.JPG"
    - "/assets/images/spa/37.JPG"
    - "/assets/images/spa/38.JPG"
    - "/assets/images/spa/39.JPG"
    - "/assets/images/spa/40.JPG"
    - "/assets/images/spa/41.JPG"
    - "/assets/images/spa/42.JPG"
    - "/assets/images/spa/43.JPG"
    - "/assets/images/spa/44.JPG"
    - "/assets/images/spa/45.JPG"
    - "/assets/images/spa/46.JPG"
    - "/assets/images/spa/47.JPG"
    - "/assets/images/spa/48.JPG"
    - "/assets/images/spa/49.JPG"
    - "/assets/images/spa/50.JPG"
    - "/assets/images/spa/51.JPG"
    - "/assets/images/spa/52.JPG"
    - "/assets/images/spa/53.JPG"
    - "/assets/images/spa/54.JPG"
    - "/assets/images/spa/55.JPG"
    - "/assets/images/spa/56.JPG"
    - "/assets/images/spa/57.JPG"
    - "/assets/images/spa/58.JPG"
    - "/assets/images/spa/59.JPG"
    - "/assets/images/spa/60.JPG"
    - "/assets/images/spa/61.JPG"
    - "/assets/images/spa/62.JPG"
    - "/assets/images/spa/63.JPG"
    - "/assets/images/spa/64.JPG"
    - "/assets/images/spa/65.JPG"
    - "/assets/images/spa/66.JPG"
    - "/assets/images/spa/67.JPG"
    - "/assets/images/spa/68.JPG"
    - "/assets/images/spa/69.JPG"
    - "/assets/images/spa/70.JPG"
    - "/assets/images/spa/71.JPG"
    - "/assets/images/spa/72.JPG"
    - "/assets/images/spa/73.JPG"
    - "/assets/images/spa/74.JPG"
    - "/assets/images/spa/75.JPG"
    - "/assets/images/spa/76.JPG"
    - "/assets/images/spa/77.JPG"
    - "/assets/images/spa/78.JPG"
    - "/assets/images/spa/79.JPG"
    - "/assets/images/spa/80.JPG"
    - "/assets/images/spa/81.JPG"
    - "/assets/images/spa/82.JPG"
    - "/assets/images/spa/83.JPG"
    - "/assets/images/spa/84.JPG"
    - "/assets/images/spa/85.JPG"
    - "/assets/images/spa/86.JPG"
    - "/assets/images/spa/87.JPG"
    - "/assets/images/spa/88.JPG"
    - "/assets/images/spa/89.JPG"
    - "/assets/images/spa/90.JPG"
    - "/assets/images/spa/91.JPG"
    - "/assets/images/spa/92.JPG"
    - "/assets/images/spa/93.JPG"
    - "/assets/images/spa/94.JPG"
    - "/assets/images/spa/95.JPG"
    - "/assets/images/spa/96.JPG"
    - "/assets/images/spa/97.JPG"
    - "/assets/images/spa/98.JPG"
    - "/assets/images/spa/99.JPG"
    - "/assets/images/spa/100.JPG"
    - "/assets/images/spa/101.JPG"
    - "/assets/images/spa/102.JPG"
    - "/assets/images/spa/103.JPG"
    - "/assets/images/spa/104.JPG"
    - "/assets/images/spa/105.JPG"
    - "/assets/images/spa/106.JPG"
    - "/assets/images/spa/107.JPG"
    - "/assets/images/spa/108.JPG"
    - "/assets/images/spa/109.JPG"
    - "/assets/images/spa/110.JPG"
    - "/assets/images/spa/111.JPG"
    - "/assets/images/spa/112.JPG"
    - "/assets/images/spa/113.JPG"
    - "/assets/images/spa/114.JPG"
    - "/assets/images/spa/115.JPG"
    - "/assets/images/spa/116.JPG"
    - "/assets/images/spa/117.JPG"
    - "/assets/images/spa/118.JPG"
    - "/assets/images/spa/119.JPG"
    - "/assets/images/spa/120.JPG"
    - "/assets/images/spa/121.JPG"
    - "/assets/images/spa/122.JPG"
    - "/assets/images/spa/123.JPG"
    - "/assets/images/spa/124.JPG"
    - "/assets/images/spa/125.JPG"
    - "/assets/images/spa/126.JPG"
    - "/assets/images/spa/127.JPG"
    - "/assets/images/spa/128.JPG"
    - "/assets/images/spa/129.JPG"
    - "/assets/images/spa/130.JPG"
    - "/assets/images/spa/131.JPG"
    - "/assets/images/spa/132.JPG"
    - "/assets/images/spa/133.JPG"
    - "/assets/images/spa/134.JPG"
    - "/assets/images/spa/135.JPG"
    - "/assets/images/spa/136.JPG"
    - "/assets/images/spa/137.JPG"
    - "/assets/images/spa/138.JPG"
    - "/assets/images/spa/139.JPG"
    - "/assets/images/spa/140.JPG"
    - "/assets/images/spa/141.JPG"
    - "/assets/images/spa/142.JPG"
    - "/assets/images/spa/143.JPG"
    - "/assets/images/spa/144.JPG"
    - "/assets/images/spa/145.JPG"
    - "/assets/images/spa/146.JPG"
    - "/assets/images/spa/147.JPG"
    - "/assets/images/spa/148.JPG"
    - "/assets/images/spa/149.JPG"
    - "/assets/images/spa/150.JPG"
    - "/assets/images/spa/151.JPG"
    - "/assets/images/spa/152.JPG"
    - "/assets/images/spa/153.JPG"
    - "/assets/images/spa/154.JPG"
    - "/assets/images/spa/155.JPG"
    - "/assets/images/spa/156.JPG"
    - "/assets/images/spa/157.JPG"
    - "/assets/images/spa/158.JPG"
    - "/assets/images/spa/159.JPG"
    - "/assets/images/spa/160.JPG"
    - "/assets/images/spa/161.JPG"
    - "/assets/images/spa/162.JPG"
    - "/assets/images/spa/163.JPG"
    - "/assets/images/spa/164.JPG"
    - "/assets/images/spa/165.JPG"
    - "/assets/images/spa/166.JPG"
    - "/assets/images/spa/167.JPG"
    - "/assets/images/spa/168.JPG"
    - "/assets/images/spa/169.JPG"
    - "/assets/images/spa/170.JPG"
    - "/assets/images/spa/171.JPG"
    - "/assets/images/spa/172.JPG"
    - "/assets/images/spa/173.JPG"
    - "/assets/images/spa/174.JPG"
    - "/assets/images/spa/175.JPG"
    - "/assets/images/spa/176.JPG"
    - "/assets/images/spa/177.JPG"
    - "/assets/images/spa/178.JPG"
    - "/assets/images/spa/179.JPG"
    - "/assets/images/spa/180.JPG"
    - "/assets/images/spa/181.JPG"
    - "/assets/images/spa/182.JPG"
    - "/assets/images/spa/183.JPG"
    - "/assets/images/spa/184.JPG"
    - "/assets/images/spa/185.JPG"
    - "/assets/images/spa/186.JPG"
    - "/assets/images/spa/187.JPG"
    - "/assets/images/spa/188.JPG"
    - "/assets/images/spa/189.JPG"
    - "/assets/images/spa/190.JPG"
    - "/assets/images/spa/191.JPG"
    - "/assets/images/spa/192.JPG"
    - "/assets/images/spa/193.JPG"
    - "/assets/images/spa/194.JPG"
    - "/assets/images/spa/195.JPG"
    - "/assets/images/spa/196.JPG"
    - "/assets/images/spa/197.JPG"
    - "/assets/images/spa/198.JPG"
    - "/assets/images/spa/199.JPG"
    - "/assets/images/spa/200.JPG"
    - "/assets/images/spa/201.JPG"
    - "/assets/images/spa/202.JPG"
    - "/assets/images/spa/203.JPG"
    - "/assets/images/spa/204.JPG"
    - "/assets/images/spa/205.JPG"
    - "/assets/images/spa/206.JPG"
    - "/assets/images/spa/207.JPG"
    - "/assets/images/spa/208.JPG"
    - "/assets/images/spa/209.JPG"
    - "/assets/images/spa/210.JPG"
    - "/assets/images/spa/211.JPG"
    - "/assets/images/spa/212.JPG"
    - "/assets/images/spa/213.JPG"
    - "/assets/images/spa/214.JPG"
    - "/assets/images/spa/215.JPG"
    - "/assets/images/spa/216.JPG"
    - "/assets/images/spa/1006.JPG"
    - "/assets/images/spa/1007.JPG"
    - "/assets/images/spa/IMG_8053.JPG"
    - "/assets/images/spa/IMG_8054.JPG"
    - "/assets/images/spa/IMG_8205.JPG"
    - "/assets/images/spa/IMG_8206.JPG"
    - "/assets/images/spa/IMG_8207.JPG"
    - "/assets/images/spa/IMG_8208.JPG"
      
- title: "Довършителни дейности"
  icon: "/assets/images/services/industrial.svg"
  description: "Финна шпакловка, машинно боядисване, декоративни мазилки, гранитогрес, каменни облицовки, вътрешни и външни мазилки."
  gallery_id: "довършителни-дейности"
  gallery_images:
    - "/assets/images/others/1.JPG"
    - "/assets/images/others/2.JPG"
    - "/assets/images/others/3.JPG"
    - "/assets/images/others/4.JPG"
    - "/assets/images/others/5.JPG"
    - "/assets/images/others/6.JPG"
    - "/assets/images/others/7.JPG"
    - "/assets/images/others/8.JPG"
    - "/assets/images/others/9.JPG"
    - "/assets/images/others/10.JPG"
    - "/assets/images/others/11.JPG"
    

- title: "ОВК, ВиК и ел. инсталации"
  icon: "/assets/images/services/infrastructure.svg"
  description: "Изграждане на ОВК, ВиК и електро инсталации, подово отопление и други специализирани инсталации."
  gallery_id: "овк-вик-и-ел-инсталации"
  gallery_images:
    - "/assets/images/ovk, vik/IMG_8001.JPG"
    - "/assets/images/ovk, vik/IMG_8002.JPG"
    - "/assets/images/ovk, vik/IMG_8066.JPG"
    - "/assets/images/ovk, vik/IMG_8067.JPG"
    - "/assets/images/ovk, vik/IMG_8351.JPG"
    - "/assets/images/ovk, vik/IMG_8352.JPG"
    - "/assets/images/ovk, vik/IMG_8353.JPG"
    - "/assets/images/ovk, vik/IMG_8354.JPG"
    - "/assets/images/ovk, vik/IMG_8355.JPG"
    - "/assets/images/ovk, vik/IMG_8356.JPG"
    - "/assets/images/ovk, vik/IMG_8443.JPG"
    - "/assets/images/ovk, vik/IMG_8444.JPG"
    - "/assets/images/ovk, vik/IMG_8445.JPG"

- title: "Архитектурно проектиране и Геодезия"
  icon: "/assets/images/services/architecture.svg"
  description: "Изготвяне на архитектурни проекти, технически чертежи и 3D визуализации."
  gallery_id: "архитектурно-проектиране"
  gallery_images:
    - "/assets/images/architecture/IMG_7990.JPG"
    - "/assets/images/architecture/IMG_7991.JPG"
    - "/assets/images/architecture/IMG_7992.JPG"
    - "/assets/images/architecture/IMG_7993.JPG"
    - "/assets/images/architecture/IMG_7994.JPG"
    - "/assets/images/architecture/IMG_7996.JPG"
    - "/assets/images/architecture/IMG_7998.JPG"
    - "/assets/images/architecture/IMG_8749.JPG"
    - "/assets/images/architecture/IMG_8750.JPG"
    - "/assets/images/architecture/IMG_8751.JPG"
    - "/assets/images/architecture/IMG_8068.JPG"
    - "/assets/images/architecture/IMG_8069.JPG"
    - "/assets/images/architecture/IMG_8070.JPG"
    - "/assets/images/architecture/IMG_8186.JPG"
    - "/assets/images/architecture/IMG_8187.JPG"
    - "/assets/images/architecture/IMG_8188.JPG"
    - "/assets/images/architecture/IMG_8189.JPG"
    - "/assets/images/architecture/IMG_8190.JPG"
    - "/assets/images/architecture/IMG_8191.JPG"
    - "/assets/images/architecture/IMG_8192.JPG"
    - "/assets/images/architecture/27.JPG"
    - "/assets/images/architecture/28.JPG"
    
    
