- title: "Жилищно строителство"
  icon: "/assets/images/services/residential.svg"
  description: "Изграждане на жилищни сгради, еднофамилни къщи, изкопи, събаряне на стари сгради, извозване на земни маси, доставка на скални фракции и др."
  gallery_id: "home"
  gallery_images:
    - "/assets/images/home/IMG_7983.JPG"
    - "/assets/images/home/IMG_7984.JPG"
    - "/assets/images/home/IMG_7985.JPG"
    - "/assets/images/home/IMG_7986.JPG"
    - "/assets/images/home/IMG_7987.JPG"
    - "/assets/images/home/IMG_7988.JPG"
    - "/assets/images/home/IMG_7989.JPG"

- title: "Ремонтни дейности"
  icon: "/assets/images/services/renovation.svg"
  description: "Вътрешни и външни цялостни и частични ремонти, покривни и дървени конструкции, фасади, хидро и топлоизолации."
  gallery_id: "ремонтни-дейности"
  gallery_images:
    - "/assets/images/reconstruction/1.JPG"

- title: "Басейни и Spa комплекси"
  icon: "/assets/images/services/commercial.svg"
  description: "Изграждане на басейни и цялостни Spa комплекси с високо качество на изпълнение."
  gallery_id: "басейни-и-spa-комплекси"
  gallery_images: []

- title: "Довършителни дейности"
  icon: "/assets/images/services/industrial.svg"
  description: "Финна шпакловка, машинно боядисване, декоративни мазилки, гранитогрес, каменни облицовки, вътрешни и външни мазилки."
  gallery_id: "довършителни-дейности"
  gallery_images: []

- title: "ОВК, ВиК и ел. инсталации"
  icon: "/assets/images/services/infrastructure.svg"
  description: "Изграждане на ОВК, ВиК и електро инсталации, подово отопление и други специализирани инсталации."
  gallery_id: "овк-вик-и-ел-инсталации"
  gallery_images: []

- title: "Архитектурно проектиране и Геодезия"
  icon: "/assets/images/services/architecture.svg"
  description: "Изготвяне на архитектурни проекти, технически чертежи и 3D визуализации."
  gallery_id: "архитектурно-проектиране"
  gallery_images:
    - "/assets/images/architecture/IMG_7990.JPG"
    - "/assets/images/architecture/IMG_7991.JPG"
    - "/assets/images/architecture/IMG_7992.JPG"
    - "/assets/images/architecture/IMG_7993.JPG"
    - "/assets/images/architecture/IMG_7994.JPG"
    - "/assets/images/architecture/IMG_7996.JPG"
    - "/assets/images/architecture/IMG_7998.JPG"
    - "/assets/images/architecture/IMG_8749.JPG"
    - "/assets/images/architecture/IMG_8750.JPG"
    - "/assets/images/architecture/IMG_8751.JPG"
    - "/assets/images/architecture/IMG_8068.JPG"
    - "/assets/images/architecture/IMG_8069.JPG"
    - "/assets/images/architecture/IMG_8070.JPG"
    - "/assets/images/architecture/IMG_8186.JPG"
    - "/assets/images/architecture/IMG_8187.JPG"
    - "/assets/images/architecture/IMG_8188.JPG"
    - "/assets/images/architecture/IMG_8189.JPG"
    - "/assets/images/architecture/IMG_8190.JPG"
    - "/assets/images/architecture/IMG_8191.JPG"
    - "/assets/images/architecture/IMG_8192.JPG"
    - "/assets/images/architecture/IMG_27.JPG"
    - "/assets/images/architecture/IMG_28.JPG"
    
    
