- title: "Жилищно строителство"
  icon: "/assets/images/services/residential.svg"
  description: "Изграждане на жилищни сгради, еднофамилни къщи, изкопи, събаряне на стари сгради, извозване на земни маси, доставка на скални фракции и др."
  gallery_id: "home"
  gallery_images:
    - "/assets/images/home/IMG_7983.JPG"
    - "/assets/images/home/IMG_7984.JPG"
    - "/assets/images/home/IMG_7985.JPG"
    - "/assets/images/home/IMG_7986.JPG"
    - "/assets/images/home/IMG_7987.JPG"
    - "/assets/images/home/IMG_7988.JPG"
    - "/assets/images/home/IMG_7989.JPG"

- title: "Ремонтни дейности"
  icon: "/assets/images/services/renovation.svg"
  description: "Вътрешни и външни цялостни и частични ремонти, покривни и дървени конструкции, фасади, хидро и топлоизолации."
  gallery_id: "ремонтни-дейности"
  gallery_images:
    - "/assets/images/reconstruction/1.JPG"
    - "/assets/images/reconstruction/2.JPG"
    - "/assets/images/reconstruction/3.JPG"
    - "/assets/images/reconstruction/4.JPG"
    - "/assets/images/reconstruction/5.JPG"
    - "/assets/images/reconstruction/6.JPG"
    - "/assets/images/reconstruction/7.JPG"
    - "/assets/images/reconstruction/8.JPG"
    - "/assets/images/reconstruction/9.JPG"
    - "/assets/images/reconstruction/10.JPG"
    - "/assets/images/reconstruction/11.JPG"
    - "/assets/images/reconstruction/12.JPG"
    - "/assets/images/reconstruction/13.JPG"
    - "/assets/images/reconstruction/14.JPG"
    - "/assets/images/reconstruction/29.1.2.JPG"
    - "/assets/images/reconstruction/29.1.3.JPG"
    - "/assets/images/reconstruction/29.1.4.JPG"
    - "/assets/images/reconstruction/29.3.JPG"
    - "/assets/images/reconstruction/29.4.JPG"
    - "/assets/images/reconstruction/29.5.JPG"
    - "/assets/images/reconstruction/29.6.JPG"
    - "/assets/images/reconstruction/29.7.JPG"
    - "/assets/images/reconstruction/29.8.JPG"
    - "/assets/images/reconstruction/IMG_8036.JPG"
    - "/assets/images/reconstruction/IMG_8037.JPG"
    - "/assets/images/reconstruction/IMG_8038.JPG"
    - "/assets/images/reconstruction/IMG_8039.JPG"
    - "/assets/images/reconstruction/IMG_8040.JPG"
    - "/assets/images/reconstruction/IMG_8041.JPG"
    - "/assets/images/reconstruction/IMG_8045.JPG"
    - "/assets/images/reconstruction/IMG_8046.JPG"
    - "/assets/images/reconstruction/IMG_8047.JPG"
    - "/assets/images/reconstruction/IMG_8048.JPG"
    - "/assets/images/reconstruction/IMG_8049.JPG"
    - "/assets/images/reconstruction/IMG_8050.JPG"
    - "/assets/images/reconstruction/IMG_8051.JPG"
    - "/assets/images/reconstruction/IMG_8052.JPG"
    - "/assets/images/reconstruction/IMG_8055.JPG"
    - "/assets/images/reconstruction/IMG_8073.JPG"
    - "/assets/images/reconstruction/IMG_8074.JPG"
    - "/assets/images/reconstruction/IMG_8075.JPG"
    - "/assets/images/reconstruction/IMG_8082.JPG"
    - "/assets/images/reconstruction/IMG_8083.JPG"
    - "/assets/images/reconstruction/IMG_8084.JPG"
    - "/assets/images/reconstruction/IMG_8085.JPG"
    - "/assets/images/reconstruction/IMG_8086.JPG"
    - "/assets/images/reconstruction/IMG_8087.JPG"
    - "/assets/images/reconstruction/IMG_8088.JPG"
    - "/assets/images/reconstruction/IMG_8089.JPG"
    - "/assets/images/reconstruction/IMG_8090.JPG"
    - "/assets/images/reconstruction/IMG_8091.JPG"
    - "/assets/images/reconstruction/IMG_8092.JPG"
    - "/assets/images/reconstruction/IMG_8093.JPG"
    - "/assets/images/reconstruction/IMG_8094.JPG"
    - "/assets/images/reconstruction/IMG_8095.JPG"
    - "/assets/images/reconstruction/IMG_8182.JPG"
    - "/assets/images/reconstruction/IMG_8183.JPG"
    - "/assets/images/reconstruction/IMG_8184.JPG"
    - "/assets/images/reconstruction/IMG_8185.JPG"
    - "/assets/images/reconstruction/IMG_8186.JPG"
    - "/assets/images/reconstruction/IMG_8168.JPG"
    - "/assets/images/reconstruction/IMG_8169.JPG"
    - "/assets/images/reconstruction/IMG_8170.JPG"
    - "/assets/images/reconstruction/IMG_8209.JPG"
    - "/assets/images/reconstruction/IMG_8210.JPG"
    - "/assets/images/reconstruction/IMG_8211.JPG"
    - "/assets/images/reconstruction/IMG_8212.JPG"
    - "/assets/images/reconstruction/IMG_8213.JPG"
    - "/assets/images/reconstruction/IMG_8214.JPG"
    - "/assets/images/reconstruction/IMG_8215.JPG"
    - "/assets/images/reconstruction/IMG_8116.JPG"
    - "/assets/images/reconstruction/IMG_8117.JPG"
    - "/assets/images/reconstruction/IMG_8379.JPG"
    - "/assets/images/reconstruction/IMG_8380.JPG"
    - "/assets/images/reconstruction/IMG_8381.JPG"
    - "/assets/images/reconstruction/IMG_8407.JPG"
    - "/assets/images/reconstruction/IMG_8406.JPG"
    - "/assets/images/reconstruction/IMG_8405.JPG"
    - "/assets/images/reconstruction/IMG_8404.JPG"
    - "/assets/images/reconstruction/IMG_8403.JPG"
    - "/assets/images/reconstruction/IMG_8401.JPG"
    - "/assets/images/reconstruction/IMG_8497.JPG"
    - "/assets/images/reconstruction/IMG_8498.JPG"
    - "/assets/images/reconstruction/IMG_8530.JPG"
    - "/assets/images/reconstruction/IMG_8529.JPG"
    - "/assets/images/reconstruction/IMG_8528.JPG"
    - "/assets/images/reconstruction/IMG_8527.JPG"
    - "/assets/images/reconstruction/IMG_8526.JPG"
    - "/assets/images/reconstruction/IMG_8526.JPG"
    - "/assets/images/reconstruction/IMG_8525.JPG"
    - "/assets/images/reconstruction/IMG_8524.JPG"
    - "/assets/images/reconstruction/IMG_8523.JPG"
    - "/assets/images/reconstruction/IMG_8522.JPG"
    - "/assets/images/reconstruction/IMG_8520.JPG"
    - "/assets/images/reconstruction/IMG_8519.JPG"
    - "/assets/images/reconstruction/IMG_8518.JPG"
    - "/assets/images/reconstruction/IMG_8517.JPG"
    - "/assets/images/reconstruction/IMG_8516.JPG"
    - "/assets/images/reconstruction/IMG_8515.JPG"
    - "/assets/images/reconstruction/IMG_8514.JPG"
    - "/assets/images/reconstruction/IMG_8513.JPG"
    - "/assets/images/reconstruction/IMG_8547.JPG"
    - "/assets/images/reconstruction/IMG_8574.JPG"
    - "/assets/images/reconstruction/IMG_8575.JPG"
    - "/assets/images/reconstruction/IMG_8576.JPG"
    - "/assets/images/reconstruction/IMG_8586.JPG"
    - "/assets/images/reconstruction/IMG_8514.JPG"
    - "/assets/images/reconstruction/IMG_8515.JPG"
    - "/assets/images/reconstruction/IMG_8516.JPG"
    - "/assets/images/reconstruction/IMG_8517.JPG"
    - "/assets/images/reconstruction/IMG_8518.JPG"
    - "/assets/images/reconstruction/IMG_8520.JPG"
    - "/assets/images/reconstruction/IMG_8521.JPG"
    - "/assets/images/reconstruction/IMG_8522.JPG"
    - "/assets/images/reconstruction/IMG_8709.JPG"
    - "/assets/images/reconstruction/IMG_8710.JPG"
    - "/assets/images/reconstruction/IMG_8711.JPG"
    - "/assets/images/reconstruction/IMG_8712.JPG"
    - "/assets/images/reconstruction/IMG_8713.JPG"
    - "/assets/images/reconstruction/IMG_8714.JPG"
    - "/assets/images/reconstruction/IMG_8715.JPG"
    - "/assets/images/reconstruction/IMG_8716.JPG"
    - "/assets/images/reconstruction/IMG_8717.JPG"
    - "/assets/images/reconstruction/IMG_8718.JPG"
    - "/assets/images/reconstruction/IMG_8719.JPG"
    - "/assets/images/reconstruction/IMG_8720.JPG"
    - "/assets/images/reconstruction/IMG_8726.JPG"
    - "/assets/images/reconstruction/IMG_8727.JPG"
    - "/assets/images/reconstruction/IMG_8728.JPG"
    - "/assets/images/reconstruction/IMG_8729.JPG"
    - "/assets/images/reconstruction/IMG_8730.JPG"
    - "/assets/images/reconstruction/IMG_8731.JPG"
    - "/assets/images/reconstruction/IMG_8732.JPG"
    - "/assets/images/reconstruction/IMG_8733.JPG"
    - "/assets/images/reconstruction/IMG_8734.JPG"
    - "/assets/images/reconstruction/IMG_8735.JPG"
    - "/assets/images/reconstruction/IMG_8736.JPG"
    - "/assets/images/reconstruction/IMG_8737.JPG"
    - "/assets/images/reconstruction/IMG_8738.JPG"
    - "/assets/images/reconstruction/IMG_8739.JPG"
    - "/assets/images/reconstruction/IMG_8740.JPG"
    - "/assets/images/reconstruction/IMG_8741.JPG"
    
- title: "Басейни и Spa комплекси"
  icon: "/assets/images/services/commercial.svg"
  description: "Изграждане на басейни и цялостни Spa комплекси с високо качество на изпълнение."
  gallery_id: "басейни-и-spa-комплекси"
  gallery_images: []

- title: "Довършителни дейности"
  icon: "/assets/images/services/industrial.svg"
  description: "Финна шпакловка, машинно боядисване, декоративни мазилки, гранитогрес, каменни облицовки, вътрешни и външни мазилки."
  gallery_id: "довършителни-дейности"
  gallery_images: []

- title: "ОВК, ВиК и ел. инсталации"
  icon: "/assets/images/services/infrastructure.svg"
  description: "Изграждане на ОВК, ВиК и електро инсталации, подово отопление и други специализирани инсталации."
  gallery_id: "овк-вик-и-ел-инсталации"
  gallery_images:
    - "/assets/images/ovk, vik/IMG_8001.JPG"
    - "/assets/images/ovk, vik/IMG_8002.JPG"
    - "/assets/images/ovk, vik/IMG_8066.JPG"
    - "/assets/images/ovk, vik/IMG_8067.JPG"
    - "/assets/images/ovk, vik/IMG_8351.JPG"
    - "/assets/images/ovk, vik/IMG_8352.JPG"
    - "/assets/images/ovk, vik/IMG_8353.JPG"
    - "/assets/images/ovk, vik/IMG_8354.JPG"
    - "/assets/images/ovk, vik/IMG_8355.JPG"
    - "/assets/images/ovk, vik/IMG_8356.JPG"
    - "/assets/images/ovk, vik/IMG_8443.JPG"
    - "/assets/images/ovk, vik/IMG_8444.JPG"
    - "/assets/images/ovk, vik/IMG_8445.JPG"

- title: "Архитектурно проектиране и Геодезия"
  icon: "/assets/images/services/architecture.svg"
  description: "Изготвяне на архитектурни проекти, технически чертежи и 3D визуализации."
  gallery_id: "архитектурно-проектиране"
  gallery_images:
    - "/assets/images/architecture/IMG_7990.JPG"
    - "/assets/images/architecture/IMG_7991.JPG"
    - "/assets/images/architecture/IMG_7992.JPG"
    - "/assets/images/architecture/IMG_7993.JPG"
    - "/assets/images/architecture/IMG_7994.JPG"
    - "/assets/images/architecture/IMG_7996.JPG"
    - "/assets/images/architecture/IMG_7998.JPG"
    - "/assets/images/architecture/IMG_8749.JPG"
    - "/assets/images/architecture/IMG_8750.JPG"
    - "/assets/images/architecture/IMG_8751.JPG"
    - "/assets/images/architecture/IMG_8068.JPG"
    - "/assets/images/architecture/IMG_8069.JPG"
    - "/assets/images/architecture/IMG_8070.JPG"
    - "/assets/images/architecture/IMG_8186.JPG"
    - "/assets/images/architecture/IMG_8187.JPG"
    - "/assets/images/architecture/IMG_8188.JPG"
    - "/assets/images/architecture/IMG_8189.JPG"
    - "/assets/images/architecture/IMG_8190.JPG"
    - "/assets/images/architecture/IMG_8191.JPG"
    - "/assets/images/architecture/IMG_8192.JPG"
    - "/assets/images/architecture/27.JPG"
    - "/assets/images/architecture/28.JPG"
    
    
